import "@radix-ui/themes/styles.css";
import './theme-config.css';
import "./globals.css";
import type { Metadata } from "next";
import {  Inter } from "next/font/google";
import { Theme } from "@radix-ui/themes";
import Navbar from "./Navbar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) { 
  return (
    <html lang="en">
      <body
        className={` ${inter.variable} antialiased`} 
      >
        <Theme accentColor="teal" grayColor="slate">
          <Navbar />
          <main className="p- ">{children}</main>
        </Theme>
      </body>
    </html>
  );
}
